_wandb:
    value:
        cli_version: 0.21.0
        e:
            6wr9rrp424c6egdom8xx9mbofiomgzj9:
                args:
                    - --data_dir
                    - ./data/processed_sequences
                    - --num_classes
                    - "3"
                    - --sequence_length
                    - "10"
                    - --epochs
                    - "100"
                    - --batch_size
                    - "1"
                    - --model_save_path
                    - ./convgru_classifier.pth
                codePath: train_classifier.py
                codePathLocal: train_classifier.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "96519835648"
                        used: "24971653120"
                email: ulix7990@gmail.com
                executable: /home/cvtech/miniconda3/envs/raft/bin/python
                git:
                    commit: cd18f705042fa1e7fd09a73e901041c3e45e85d4
                    remote: https://github.com/ulix7990/RAFT_US.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-0edf63fb-9594-30ee-b2fd-213c3b640956
                host: cvtech
                memory:
                    total: "33379823616"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.17
                program: ./train_classifier.py
                python: CPython 3.8.20
                root: /home/cvtech/rmc_slump_ws/RAFT_US
                startedAt: "2025-07-30T03:17:51.602209Z"
                writerId: 6wr9rrp424c6egdom8xx9mbofiomgzj9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
                - 61
                - 62
            "4": 3.8.20
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 1
data_dir:
    value: ./data/processed_sequences
epochs:
    value: 100
learning_rate:
    value: 0.001
model_save_path:
    value: ./convgru_classifier.pth
num_classes:
    value: 3
sequence_length:
    value: 10
